from .terrestrial import ITerrestrial
from .freshwater import IFreshwater
from .aquatic import IAquatic
from .flying import IFlying
from .walking import IWalking
from .swimming import ISwimming
from .saltwater import ISaltwater
from .identifiable import Identifiable
from .biome.contains_animals import IContainsAnimals
from .biome.contains_plants import IContainsPlants
from .saltwater import ISaltwater
from .high_elevation import IHigh_Elevation
